### ISSUE TITLE
different results of pairwise.adonis based on same data

### ISSUE THREAD

**Issue by JaneDY** [pmartinezarbizu/pairwiseAdonis#12]
Hello！
I tried pairwise.adonis function based on same datasets two times, but got different results. Has anyone encountered the same problem and known why?

**Comment by pmartinezarbizu** [comment]
Can you please submit an example, so we can reproduce the issue?
Pedro

**Comment by pmartinezarbizu** [comment]
You should get same F values etc, but p-values may differ from run to run as they are based on permutations
