### ISSUE TITLE
Pairwise adonis test with phyloseq object and a unifrac distance matrix?

### ISSUE THREAD

**Issue by Stabilo12** [pmartinezarbizu/pairwiseAdonis#15]
I would like to perform a pairwise adonis test with phyloseq object and a unifrac distance matrix but I don't know how? Does somebody know if this is possible within this function?

Example:
data(GlobalPatterns)
metadata <- as(sample_data(GlobalPatterns), "data.frame")
dist.uf <- phyloseq::distance(GlobalPatterns, method = "unifrac")
ps.adonis <- adonis(dist.uf ~ SampleType, data = metadata, perm=9999)

SampleType 8 3.4957 0.43696 4.2046 0.66427 1e-04 ***

The adonis test showed that SampleType does explain part of the variation, but I want to know which Samples are different from each other.. With betadisper paired test is easy to perform, but I don't know how to do this within the adonis function with a uf distance matrix?

ps.disper <- betadisper(dist.uf, metadata$SampleType)
permutest(ps.disper, pair=TRUE)

Response: Distances
Df Sum Sq Mean Sq F N.Perm Pr(>F)
Groups 8 0.042397 0.0052996 2.9572 999 0.027 *
Residuals 17 0.030466 0.0017921

Signif. codes: 0 ‘’ 0.001 ‘’ 0.01 ‘’ 0.05 ‘.’ 0.1 ‘ ’ 1

Pairwise comparisons:
![image](https://user-images.githubusercontent.com/37101233/65871904-b5164c80-e37f-11e9-9a30-59409d14b26d.png)

**Comment by maayanster** [comment]
I too would like this!

**Comment by pmartinezarbizu** [comment]
You can use a distance matrix and a vector of factors.
So oyu can enter your Unifrac distance matrix created by another package and a vector with your factors.
Pedro

**Comment by Jigyasa3** [comment]
Hey  @pmartinezarbizu ,@Stabilo12 

I am interested in similar analysis. So I made slight changes in the pairwise.adonis() function.


`pairwise.adonis <- function(x,factors, sim.method = 'bray', p.adjust.m ='bonferroni')
{
library(vegan)
co = combn(unique(factors),2)
pairs = c()
F.Model =c()
R2 = c()
p.value = c()
for(elem in 1:ncol(co)){
#ad = adonis(x[factors %in% c(co[1,elem],co[2,elem]),] ~ factors[factors %in% c(co[1,elem],co[2,elem])] , method =sim.method); #original adonis function
ad= adonis(x~ factors); #the original adonis function is modified here
pairs = c(pairs,paste(co[1,elem],'vs',co[2,elem]));
F.Model =c(F.Model,ad$aov.tab[1,4]);
R2 = c(R2,ad$aov.tab[1,5]);
p.value = c(p.value,ad$aov.tab[1,6])
}
p.adjusted = p.adjust(p.value,method=p.adjust.m)
pairw.res = data.frame(pairs,F.Model,R2,p.value,p.adjusted)
return(pairw.res)
}


##get output-
out<-pairwise.adonis(tree_dist,data$V2)
` 
tree_dist -> the distance matrix from tree file
data$V2 -> a categorical variable with rownames matching the tree$tip.labels.

@pmartinezarbizu , what do you think, is this small variation in the code correct?

**Comment by pmartinezarbizu** [comment]
Does it work for you?
I wonder, if you put 
ad= adonis(x~ factors); #
how are you iterating along pairwise combination of factors?
Pedro

**Comment by Jigyasa3** [comment]
@pmartinezarbizu , It seems to be working. The output gives a pairwise comparison. Attaching a tree file and the factors variable [https://drive.google.com/drive/folders/1f98zQkQDpr_p7_35HoEeJia7tgYv0HI0?usp=sharing](url)

**Comment by pmartinezarbizu** [comment]
I cannot open your attachment

**Comment by pmartinezarbizu** [comment]
BUt anyway, if it works, what is your question? Do you think that the output is wrong?

**Comment by pmartinezarbizu** [comment]
can you post the output
>out

**Comment by Jigyasa3** [comment]
Yes, I wanted to confirm if the modification is not giving an error.
Here is the output-
"","pairs","F.Model","R2","p.value","p.adjusted"
"1","diet2 vs diet3",1.63931389216849,0.0263812679846003,0.04,0.12
"2","diet2 vs diet1",1.63931389216849,0.0263812679846003,0.039,0.117
"3","diet3 vs diet1",1.63931389216849,0.0263812679846003,0.046,0.138

**Comment by pmartinezarbizu** [comment]
Hello the F.Model value and R2 values are exactly the same in all comparisons. But the p-value is different. This is very strange. I would be careful with this result.

I still doenst understand the problem (sorry for that):
Why you do not use your distance matrix "tree_dist" and your vector of factors "data$V2" with the original pairwise.adonis function? Are you getting an error?
If you want you can send me your objects "tree_dist" and  "data$V2" by email.

pmartinez@senckenberg.de

**Comment by pmartinezarbizu** [comment]
Ok Jigyasa3,
your function is wrong. You are nor iterating trough the pairs of factors.

See the result of the original function:
> pairwise.adonis(iris[,1:4],iris$Species)
                    pairs Df SumsOfSqs    F.Model        R2 p.value p.adjusted sig
1    setosa vs versicolor  1 1.1937545  552.51266 0.8493496   0.001      0.003   *
2     setosa vs virginica  1 2.0713706 1001.54509 0.9108722   0.001      0.003   *
3 versicolor vs virginica  1 0.2108291   91.82959 0.4837475   0.001      0.003   *

See the result of your function (i renamed it in pairwise.adonis3):
> pairwise.adonis3(iris[,1:4],iris$Species)
                    pairs  F.Model        R2 p.value p.adjusted
1    setosa vs versicolor 532.7426 0.8787614   0.001      0.003
2     setosa vs virginica 532.7426 0.8787614   0.001      0.003
3 versicolor vs virginica 532.7426 0.8787614   0.001      0.003

You see, you get exactly the same values in all pairs, which is wrong.

**Comment by pmartinezarbizu** [comment]
Please run 

pairwise.adonis(tree_dist,data$V2)
with the original function and send me the result.
Pedro

**Comment by Jigyasa3** [comment]
dear @pmartinezarbizu 

Thank you so much for replying! I really appreciate it. It turns out I was using your older version of the script available here [https://www.researchgate.net/post/How_can_I_do_PerMANOVA_pairwise_contrasts_in_R](url)

The current version available on github allows "x" to be a distance matrix that solves my problem.
#output from the github version of the script-
`           pairs Df  SumsOfSqs  F.Model          R2 p.value p.adjusted sig
1 diet1 vs diet2  1 0.10560295 5.108806 0.009088643   0.014      0.042   .
2 diet1 vs diet3  1 0.18734907 9.162948 0.018579960   0.002      0.006   *
3 diet2 vs diet3  1 0.08388262 3.795938 0.035543847   0.029      0.087
`

The main reason I was looking for a modification of your script was that I am interested in examining the correlation between an ecological variable (eg-diet) directly on a ML tree. I do not have counts data as shown in the Iris example.

Sorry for causing you trouble. I should have checked the current version before proposing anything new.

Thanks again!

**Comment by pmartinezarbizu** [comment]
OK, perfect. Thank you Jigyasa3 .
So I can close this issue,
Pedro
