### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by confusedstudent99** [pmartinezarbizu/pairwiseAdonis#16]
Hello people,
I am new to R and I am trying to install the pairwiseAdonis package for a school project. However, I keep getting the following error message:

** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package 'vegan' required by 'pairwiseAdonis' could not be found
Execution halted
ERROR: lazy loading failed for package 'pairwiseAdonis'
* removing 'C:/Users/julie/Documents/R/win-library/3.6/pairwiseAdonis'
Error: Failed to install 'pairwiseAdonis' from GitHub:

There seems to be an issue with installing 'vegan'. Could you suggest what I can do to solve this?

Thank you!

**Comment by pmartinezarbizu** [comment]
Please install package vegan first.
