### ISSUE TITLE
pairwise.adonis from distance matrix issue

### ISSUE THREAD

**Issue by mnhuda** [pmartinezarbizu/pairwiseAdonis#17]
Hello Pedro,

I was trying to do pairwise Adonis from the distance matrix and getting the error message “incorrect number of dimensions”. 
...
data(iris)
dist_matrix=vegdist(iris[,1:4],method="euclidean")
pairwise.adonis(dist_matrix,factors=iris$Species,
                p.adjust.m='holm')
...
Regards,
Nazmul

**Comment by pmartinezarbizu** [comment]
Works fine for me with your script.
Please update to latest version from github
pedro
