### ISSUE TITLE
installing pairwiseAdonis

### ISSUE THREAD

**Issue by jrfrun** [pmartinezarbizu/pairwiseAdonis#18]
having problem installing pairwiseAdonis, I basically use the command

devtools::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")

R does something and returns the following

Downloading GitHub repo pmartinezarbizu/pairwiseAdonis@master
  
  
  
   checking for file 'C:\Users\jrferreira\AppData\Local\Temp\Rtmp4Apu0C\remotes1fa06709434f\pmartinezarbizu-pairwiseAdonis-af50233\pairwiseAdonis/DESCRIPTION' ...
  
   checking for file 'C:\Users\jrferreira\AppData\Local\Temp\Rtmp4Apu0C\remotes1fa06709434f\pmartinezarbizu-pairwiseAdonis-af50233\pairwiseAdonis/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\jrferreira\AppData\Local\Temp\Rtmp4Apu0C\remotes1fa06709434f\pmartinezarbizu-pairwiseAdonis-af50233\pairwiseAdonis/DESCRIPTION' (1.2s)

  
  
  
-  preparing 'pairwiseAdonis':
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information

  
  
  
-  checking for LF line-endings in source and make files and shell scripts

  
  
  
-  checking for empty or unneeded directories

  
  
  
-  building 'pairwiseAdonis_0.0.1.tar.gz'

  
   

Error: Failed to install 'pairwiseAdonis' from GitHub:
  (converted from warning) package ‘pairwiseAdonis’ is in use and will not be installed
> 
any help is welcomed

**Comment by pmartinezarbizu** [comment]
did you solve the problem?
Pedro

**Comment by jrfrun** [comment]
yes I did
thank you

    On Wednesday, October 21, 2020, 7:58:51 AM PDT, Pedro Martinez Arbizu <notifications@github.com> wrote:  
 
 


did you solve the problem?
Pedro
