### ISSUE TITLE
Issue when running pairwise.adonis

### ISSUE THREAD

**Issue by PabloBros** [pmartinezarbizu/pairwiseAdonis#20]
Hi,

When running your example 
pairwise.adonis(iris[,1:4],iris$Species)

I obtained an error message:
 Error in adonis(x[factors %in% c(as.character(co[1, elem]), as.character(co[2,  : 
 l'argument "sim.method" est manquant, avec aucune valeur par défaut

Maybe there is something wrong with R 4.0 ?

Pablo

**Comment by pmartinezarbizu** [comment]
HI Pablo, sorry I am not always lloking into Github.
Did you solve the problem?
Pedro
