### ISSUE TITLE
Not working for interactions between factors?

### ISSUE THREAD

**Issue by shaynasura** [pmartinezarbizu/pairwiseAdonis#21]
Hello,

I have a two-factor experimental design. My factors are Community, which has 4 levels, and Nutrient Treatment, which has 3 levels.
Factors: levels
Community: alone, with species 1, with species 2, all 3
Nutrient Treatment: ambient, press, pulse

Adonis indicates I have a significant interaction between my 2 factors, so I am trying to use pairwise.adonis2 to do posthoc tests and find out where the differences are between all of my treatments (4 levels * 3 levels = 12 levels).

Is pairwise.adonis2 working for posthoc tests on significant interactions terms? Or is it only working for main effects and strata?

If it is working for interaction terms, I can't seem to get it to work for assessing comparisons between all treatments. I've tried using the "strata" but it doesn't give me every combination of my treatments. It separates it out for one of my factors, and then gives an ANOVA table for each comparison of levels within that factor. But I don't know which level of the other factor it is for. I'm also not sure how to interpret the full ANOVA table output when comparing between 2 treatments....I was hoping for output like what is produced by pairwise.adonis().

My call is this: pairwise.adonis2(Padina_dist~Community*Nutrient_Treatment,data=Padina_3)

and then I get output like this:

$parent_call
[1] "Padina_dist ~ Nutrient_Treatment * Community , strata = Community"

$`Ambient _vs_Press `
Blocks:  with(mdat1, mdat1[, ststri]) 
Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                             Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nutrient_Treatment            1   11674.2 11674.2  85.309 0.50023  0.001 ***
Community                     3     965.1   321.7   2.351 0.04136  0.001 ***
Nutrient_Treatment:Community  3    1119.0   373.0   2.726 0.04795  0.058 .  
Residuals                    70    9579.2   136.8         0.41046           
Total                        77   23337.5                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

$`Ambient _vs_Pulse`
Blocks:  with(mdat1, mdat1[, ststri]) 
Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                             Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nutrient_Treatment            1    2691.4 2691.39 11.5005 0.10518  0.001 ***
Community                     3    4726.4 1575.48  6.7321 0.18471  0.004 ** 
Nutrient_Treatment:Community  3    2023.3  674.43  2.8819 0.07907  0.061 .  
Residuals                    69   16147.6  234.02         0.63104           
Total                        76   25588.7                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

$`Press _vs_Pulse`
Blocks:  with(mdat1, mdat1[, ststri]) 
Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                             Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nutrient_Treatment            1    3160.3  3160.3 13.0858 0.12270  0.001 ***
Community                     3    2050.5   683.5  2.8302 0.07962  0.014 *  
Nutrient_Treatment:Community  3    3397.8  1132.6  4.6897 0.13192  0.009 ** 
Residuals                    71   17146.8   241.5         0.66576           
Total                        78   25755.3                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

attr(,"class")
[1] "pwadstrata" "list"      

Any help is appreciated!

**Comment by pmartinezarbizu** [comment]
Hello,
 >I've tried using the "strata" but it doesn't give me every combination of my treatments
No it will only give you the combinations of levels in the first factor mentioned in the formula.
Pedro
