### ISSUE TITLE
Problems installing the package

### ISSUE THREAD

**Issue by ThiagoRBM** [pmartinezarbizu/pairwiseAdonis#22]
Hello,

I can't install the package, I get the following error: 

Downloading GitHub repo pmartinezarbizu/pairwiseAdonis@HEAD
Error: Failed to install 'pairwiseAdonis' from GitHub:
  System command 'Rcmd.exe' failed, exit status: -1, stdout + stderr empty

Do you know what Rcmd.exe means?

I'm working on R 3.6 and have Rtools installed also.

**Comment by pmartinezarbizu** [comment]
NO I dot know.
Do you have Rtools installed?
PEdro
