### ISSUE TITLE
Incorrect number of dimensions pairwise adonis on phyloseq object

### ISSUE THREAD

**Issue by wlwhalley** [pmartinezarbizu/pairwiseAdonis#24]
Hi, 

I keep getting this error and I do not understand it 
I have a distance matrix from a phyloseq object and a factor that contains managements, the code is: 

```
dist<-phyloseq::distance(ps5, method = "bray") 

vegan::adonis(dist ~ metadata$manage, permutation = 9999, na.rm=TRUE) 

pairwise.adonis(dist, metadata$manage) 
```
`

The adonis works but the pairwise.adonis comes back with the error:
`Error in x[factors %in% c(co[1, elem], co[2, elem]), ] : 
  incorrect number of dimensions`

I don't understand - looking at metadata$manage it's just a normal factor

**Comment by pmartinezarbizu** [comment]
HI, can you send me an example of your data?

**Comment by pmartinezarbizu** [comment]
If problem persists pelse contact me. Pedro
