### ISSUE TITLE
pairwise.adonis2 output: adjusted p vals?

### ISSUE THREAD

**Issue by Malytherin** [pmartinezarbizu/pairwiseAdonis#26]
Hi Pedro,

Data overview: I am measuring beta diversity metrics (ex. Bray Curtis) for fecal samples from 6 individuals (Fecal.ID) collected at different time points (SampleDay).

_bray_S6 <- phyloseq::distance(S6, "bray")_

First I defined my permutation blocks by individual (Fecal.ID) for the PERMANOVA
_permS6 <- how(nperm = 999)
setBlocks(permS6) <- with(dfS6, Fecal.ID)
adonis2(bray_S6 ~ SampleDay, data = dfS6, permutations = permS6)_

I am using pairwise.adonis2 function to check the pairwise comparisons between day 0 and the other sample days. Ex. Is day 0 different from day 1? Is day 0 different from day 2? Etc.

`_pairwise.adonis2(bray_S6` ~ SampleDay, data = dfS6, strata = `'Fecal.ID')_`

The output looks like this (only with many more comparisons):

[1] "bray_S6 ~ SampleDay , strata = Fecal.ID"

$`Day 0_vs_Day 1`
Blocks:  with(mdat1, mdat1[, ststri]) 
Permutation: free
Number of permutations: 63

Terms added sequentially (first to last)

```
 Df           SumsOfSqs           MeanSqs      F.Model     R2              Pr(>F)  
SampleDay  1      0.4961         0.49610      1.9636     0.16413       0.03125 *
Residuals   10    2.5265          0.25265      0.83587          
Total     11    3.0226      1.00000          
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1 
```     

.
.
.
etc.

**QUESTION: Is this pairwise.adonis2 p-value (0.03125) adjusted? If yes, is there a way to get the unadjusted value?** 

**Extra question: Is there a way to reduce or restrict the pairwise comparisons in pairwise.adonis2 to only the comparisons I'm interested in? Ex. Restrict to only comparing Day 0 to every other day and NOT comparing Day 1 to Day 2, 3, 4, etc?** I know this can be done in pairwise.adonis with _reduce = "Day 0"_ but I did not see this function for pairwise.adonis2.

Thank you!

**Comment by pmartinezarbizu** [comment]
Hello, NO in pairwise.adonis2 is not adjusting p-values, You need to do it by hand .

>Extra question: Is there a way to reduce or restrict the pairwise comparisons in pairwise.adonis2 to only the comparisons I'm interested in? Ex.

NO, in this case I would suggest you reduce your matrix forehand and then apply pairwise.adonis2.
This may give you also more control of what you are doing.
regards pe

**Comment by pauGuas** [comment]
Hi, what kind of adjustment does this use for the p value?

**Comment by pmartinezarbizu** [comment]
in pairwise.adonis you can choose any adjustment offered by function padjust, in pairwise.adonis2 this option is not available.

**Comment by pmartinezarbizu** [comment]
read the help file

**Comment by OndroV** [comment]
Hi, I'm wondering if it's more appropriate to use p.adjust on all the p-values obtained from pairwise.adonis2; or just within the pairs. Example:

`pvals         # all the p-values from pairwise.adonis2(y ~ A + B + C) , where A has 3 levels`
0.002 0.007 0.020 0.001 0.040 0.511 0.001 0.009 0.032 
`p.adjust(pvals, method = "holm")          # all adjusted `
0.014 0.042 0.080 0.009 0.096 0.511 0.009 0.045 0.096 
`p.adjust(pvals[1:3], method = "holm")         # adjusted within the first pair of levels`
0.006 0.014 0.020
