### ISSUE TITLE
(not)running pairwise.adonis2 with mapply

### ISSUE THREAD

**Issue by PedroBeschoren** [pmartinezarbizu/pairwiseAdonis#28]
Hello, Pedro!

I'm having trouble applying pairwise.adonis2 to a list of phyloseq objects with mapply. 

My objective is to automate this for long lits & make it available/comprehensible to students. I've been trying to solve this for several hours;  you will find below the best example I can provide you. When it runs, I have the error message " Error in `[.formula`(eval(lhs), rhs.frame[, 1] %in% c(co[1, elem], co[2,  : 
  unused argument (alist()) "

I have no idea of which unused argument it is talking about, but it is not something I placed in the function. I understand your function is under development and you may take time to reply.

As you can see the same formula & data works if apply to individual list components. For now, I can only run pairwise.adonis2 dozens of times, once for each list component.

Any idea of how can this be fixed? thanks!

```
library(vegan)
library(pairwiseAdonis)
library(phyloseq) # manages microbiome datasets and phyloseq objects
library(metagMisc) #  lets you create lists of split phyloseq objects
data(soilrep)
sample_data(soilrep)

pslist<-phyloseq_sep_variable(soilrep, variable = "clipped") # list of phyloseq objects

listed_bray <-lapply(pslist, function (x) # lhs data
  phyloseq::distance(otu_table(x), method="bray"))

listed_sampledata <-lapply(pslist, function (x) # rhs metadata
  as(phyloseq::sample_data(x),"data.frame"))

# using pairwise.adonis2 on each element of the list works!
pairwise.adonis2(listed_bray[[1]] ~ Treatment*warmed, data = listed_sampledata[[1]])

# using pairwise.adonis2 over lists fails!
mapply(function (x,y) 
  pairwise.adonis2(x ~ Treatment*warmed, data = y),
  listed_bray, listed_sampledata, SIMPLIFY = FALSE)

```

**Comment by pmartinezarbizu** [comment]
Hello we have done some updates in both functions. Please install and try again.

pairwiseAdonis is just a wrapper around adonis2. Can you run this list using adonis2 ?
Sorry I am not an expert in how to use mapply
pe
