### ISSUE TITLE
Can't install install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")

### ISSUE THREAD

**Issue by cmazier** [pmartinezarbizu/pairwiseAdonis#31]
Hello,

I can't install pairwiseAdonis (install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")). I have already had this problem because I have an "è" in the path of the installation. I cant' change this, have you another way to install pairwise adonis, please ?

Thank you

**Comment by RossanaMaguina** [comment]
try Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
before installing pairwise.adonis
More info bellow

https://www.reddit.com/r/rstats/comments/gmlep7/installing_from_github/
