### ISSUE TITLE
Does pairwise.adonis2 adjust p-vals?

### ISSUE THREAD

**Issue by Abbie-Williams** [pmartinezarbizu/pairwiseAdonis#35]
Hi, 

I was reading the man page for your function. I noticed that the first iteration of pairwise.adonis has adjustment of p-value for multiple comparisons. This isn't mentioned in the notes for pairwise.adonis2. The output seems to suggest that it is a raw, uncorrected p-value. I just wanted to double check if that was the case, and we need to follow up with p-value correction?

**Comment by Malytherin** [comment]
Just to help you out, I asked this question earlier: https://github.com/pmartinezarbizu/pairwiseAdonis/issues/26

and it seems the p-value from adonis2 is NOT adjusted. You will have to do it yourself.

Hope that helps!
