### ISSUE TITLE
unable to find adonis2

### ISSUE THREAD

**Issue by erifa1** [pmartinezarbizu/pairwiseAdonis#37]
Hello
https://github.com/pmartinezarbizu/pairwiseAdonis/blob/ece560d2364992e5751bd31431f505805e29f73d/pairwiseAdonis/R/pairwise.adonis.R#L52

adonis2 needs to be imported with
```
 #'@importFrom vegan adonis2 vegdist 
```
Maybe this is needed for pairwise.adonis2.R too.
Best !

**Comment by pmartinezarbizu** [comment]
thanks
