### ISSUE TITLE
PERMANOVA with small sample size?

### ISSUE THREAD

**Issue by marwa38** [pmartinezarbizu/pairwiseAdonis#40]
Hi guys 
This is not a technical question but asking for maybe advice or helpful comment.
Could you please let me know what are the lowest sample size that could be considered acceptable? I did the ordination plot and can see the difference/dissimilarity visually between intestine, feed, and water.

The problem is that I have n=2 or n=3 in water/feed that I suspect the PERMANOVA results.
Please comment and tell me what you think.

**Comment by pmartinezarbizu** [comment]
If you ask me with 3-4 samples you are at the lower limmit of replication. Results will depend on how difference the blocks are that you are comparing. If you plan an experiment from scratch always try to get 5 or more replicates.
