### ISSUE TITLE
I can't install pairwiseAdonis

### ISSUE THREAD

**Issue by dnavroski** [pmartinezarbizu/pairwiseAdonis#41]
I'm having trouble installing the package

I followed the steps:

install.packages('devtools')
library(devtools)
install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")

but the following error appears:

Downloading GitHub repo pmartinezarbizu/pairwiseAdonis@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/pmartinezarbizu/pairwiseAdonis/tarball/HEAD'

Can someone help me?

**Comment by pmartinezarbizu** [comment]
>cannot open URL
Your internet connection working? and no firewall?
pe
