### ISSUE TITLE
Multiple factors in pairwiseAdonis2

### ISSUE THREAD

**Issue by Malytherin** [pmartinezarbizu/pairwiseAdonis#42]
Hi Pedro,

I am looking at fecal microbiota data over multiple days. I have Fecal.ID (8 individuals each sampled for multiple days), SampleDay (which day of the series it was sampled; 6 levels = Day 0, Day 1, etc.), and LifeStage (2 levels = adult or juvenile). 

I first ran adonis2:
`permS8 <- how(nperm = 999)`
`setBlocks(permS8) <- with(dfS8, Fecal.ID)`
`adonis2(bray_S8 ~ SampleDay + LifeStage, data = dfS8, permutations = permS8)`

And both SampleDay and LifeStage were significant.

I then ran pairwise.adonis2:
`pairwise.adonis2(bray_S8 ~ SampleDay + LifeStage, data = dfS8, strata = 'Fecal.ID')`

But I am confused about the interpretation of the output. Here is a small selection of the output:
`$parent_call`
`[1] "bray_S8 ~ SampleDay + LifeStage , strata = Fecal.ID , permutations 999"`

`$Day 0_vs_Day 1`
`                    Df  SumOfSqs       R2             F          Pr(>F)       `
`        SampleDay   1     0.4172      0.09366       1.5319   0.007812 **                `
`        LifeStage   1     0.4967        0.11152      1.8240   0.007812 ** `
`        Residual    13    3.5402        0.79482         `               
`        Total        15    4.4541         1.00000         `

For the above output with two factors, does this particular part of the output mean that my Bray Curtis distances (bray_S8) in Day 0 vs Day 1 samples are significantly different by SampleDay (p=0.007812) AND also by Lifestage (p=0.007812)? Meaning the Bray Curtis change between Day 0 and Day 1 was influenced by time (SampleDay) and whether the individual was an adult or a juvenile (LifeStage)? 

Thank you for any help you can provide.

**Comment by user3386170** [comment]
I have the same question.

**Comment by pmartinezarbizu** [comment]
Hi @Malytherin  I am sorry that I have absolutelly no time to answer questions about interpretation of particular analyses. I would need to get the data and play around myself.

> are significantly different by SampleDay (p=0.007812) AND also by Lifestage (p=0.007812)? Meaning the Bray Curtis change between Day 0 and Day 1 was influenced by time (SampleDay) and whether the individual was an adult or a juvenile 

I would say yes. but again i have not checked your data. Please consult a statistitian at your place
