### ISSUE TITLE
Stratum not working correctly?

### ISSUE THREAD

**Issue by Gvash** [pmartinezarbizu/pairwiseAdonis#8]
Hello,
Thank you for your efforts in making pairwiseAdonis available.
I've been trying to use the 'stratum' argument to pairwise.adonis, but it isn't working as I'd expect.
e.g.
>pairwise.adonis(CountData,factors=Treat,stratum=Site)
Only gives me pairwise comparisons of Treat(ment)s

>pairwise.adonis(CountData,factors=paste(Treat,Site),stratum=Site)
Returns pairwise comparisons of ALL Treat:Site combinations, not Treat constrained within Site, as I would expect.
Are my expectations wrong or is there something wrong with the script for stratum?
Thank you!

**Comment by pmartinezarbizu** [comment]
Install pairwise.adonis2
this is supporting strata
