### ISSUE TITLE
Interactions on pairwise.adonis2

### ISSUE THREAD

**Issue by valybionda** [pmartinezarbizu/pairwiseAdonis#9]
Hi,
I was trying to use the "pairwise.adonis2" on an interaction of two factors F1 and F2. F1 has 2 levels while F2 has 3 levels. I dont get the results of the function as only calculate F1L1 vs F1L2 without giving information about the levels of F2.
In ?pairwise.adonis2 nothing is explained about the interaction.
Am I missing something? strata?

Thank you
Valentina

```
> pairwise.adonis2(sqrt(data[5:33]) ~ F1* F2, 
+                  data=data[1:3])
$parent_call
[1] "sqrt(data[5:33]) ~ F1* F2 , strata = Null"

$F1L1_vs_F1L2
Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                         Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
F1                     1   0.15523 0.15523  7.5476 0.07162  0.001 ***
F2                     2   0.70157 0.35078 17.0560 0.32370  0.001 ***
F1:F2                 2   0.19994 0.09997  4.8607 0.09225  0.001 ***
Residuals         54   1.11059 0.02057         0.51243           
Total                59   2.16732                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

attr(,"class")
[1] "pwadstrata" "list"
```

**Comment by pablo-bernal** [comment]
Hi valybionda,

I am having the same issue. Did you find a solution / answer for it?

Thank you!

Pablo

**Comment by valybionda** [comment]
Hi Pablo,
unfortunately no solution and you are the first person that was answering!
at the end I was re-doing the permanova with P**ER....

If you find something, let me know.

Vale

**Comment by sbiffi2** [comment]
Same issue here unfortunately

**Comment by valybionda** [comment]
did someone find some solutions?

**Comment by pmartinezarbizu** [comment]
Hi Valentina and Pablo,
I clearly state in the front page:

'NOTE: This is still a raw developing version -- results may not be rigth. I would appreciate feed back.!

This is because I am not sure the the fuction is calculating everything rigth, I would appreciate if you could send me an example dataset, a formula and an example result. So I can start understanding how it should be. My function is just a wrapper around adonis. But the formula seems to be complicated to formulate with iterations and strata. I am a bit lost, I must admit.

Pedro

**Comment by valybionda** [comment]
Hi Pedro,
sorry but after more than 1 year I don't recall the dataset...
You can try with a "random" dataset, test the interactions and if you want, post here the results.

Thank you
Valentina

**Comment by pmartinezarbizu** [comment]
>sorry but after more than 1 year I don't recall the dataset...
So the problem is solved?
How did you solve the problem?, if you share your solution this will help everybody.
Pedro

**Comment by fabioweiss** [comment]
Same issue here. I have two factor variables. F1 (two levels) and F2 (three levels). I tested them as interaction using vegan::adonis2 and the interaction comes up significant.

When I run pairwise.adonis2 with F1*F2 it will only compare the two levels of F2. My work-around for now is to create a new factor variable with the combinations of F1 and F2 yielding six groups (2 by 3) and throw this into pairwise.adonis2. By the way, I have use the same work-around for PERMDISP/betadisper.

Thanks for the package, @pmartinezarbizu :)
